### ISSUE TITLE
[Query] What is it?

### ISSUE THREAD

**Issue by Cobwebster** [PrismarineJS/diamond-square#1]
Hey,

I couldn't find much documentation on this but it looks really good from what I can tell,

What is the purpose of this? Can I provide a user interface to pass in seeds and have it generate the world in a web view? Or am I completely missing the meaning.

**Comment by rom1504** [comment]
Hi,

This is a generator for prismarine-world which is the world implementation
for flying-squid which is a minecraft server.

It would be possible to make a browser viewer for prismarine-world yeah if
you wanted. Would be cool
